const styles = {
  container: {},
  month: {},
  navbar: {},
  navButton: {},
  navButtonPrev: {},
  navButtonNext: {},
  caption: {},
  weekdays: {},
  weekdaysRow: {},
  weekday: {},
  body: {},
  week: {},
  day: {},
  interactionDisabled: {},
  today: {},
  selected: {},
  disabled: {},
  outside: {},
};

export default {
  container: styles.container,
  interactionDisabled: styles.interactionDisabled,
  month: styles.month,
  navBar: styles.navbar,
  navButtonPrev: styles.navButtonPrev,
  navButtonNext: styles.navButtonNext,
  caption: styles.caption,
  weekdays: styles.weekdays,
  weekdaysRow: styles.weekdaysRow,
  weekday: styles.weekday,
  body: styles.body,
  week: styles.week,
  day: styles.day,
  today: styles.today,
  selected: styles.selected,
  disabled: styles.disabled,
  outside: styles.outside,
};
